/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { registerSingleton } from '../../../../../../platform/instantiation/common/extensions.js';
import { InstantiationType } from '../../../../../../platform/instantiation/common/instantiation.js';
import { IAgentProfileManager, AgentProfileManager } from './agentProfileManager.js';
import { ICouncilOrchestrator, CouncilOrchestrator } from './councilOrchestrator.js';
import { IConsensusManager, ConsensusManager, IterationGuard } from './councilCoordinator.js';
import { IEvidenceValidator, EvidenceValidator } from './evidenceValidator.js';
import { IAdvancedConsensusEngine, AdvancedConsensusEngine } from './advancedConsensusEngine.js';
import { IDebateResolver, DebateResolver } from './debateResolver.js';
import { ICouncilTestRunner, CouncilTestRunner } from './councilTestRunner.js';
import { ICouncilMCPIntegration, CouncilMCPIntegration } from './councilMCPIntegration.js';
import { IRedTeamAgent, RedTeamAgent } from './redTeamAgent.js';
import { ICouncilCIRunner, CouncilCIRunner } from './councilCIRunner.js';
import { ICouncilMemoryGraph, CouncilMemoryGraph } from './councilMemoryGraph.js';
import { ICouncilPolicyEngine, CouncilPolicyEngine } from './councilPolicies.js';
import { ICouncilPRReviewBoard, CouncilPRReviewBoard } from './councilPRReview.js';
import { ICouncilGovernance, CouncilGovernance } from './councilGovernance.js';
import { ICouncilEnterprise, CouncilEnterprise } from './councilEnterprise.js';
import { ICouncilSmartAgentSelector, CouncilSmartAgentSelector } from './councilSmartAgentSelector.js';
import { ICouncilModelRouter, CouncilModelRouter } from './councilModelRouter.js';
import { ICouncilSecretDetector, CouncilSecretDetector } from './councilSecretDetector.js';
import { ICouncilInputSanitizer, CouncilInputSanitizer } from './councilInputSanitizer.js';
import { ICouncilNotificationService, CouncilNotificationService } from './councilNotificationService.js';
import { ICouncilCostTracker, CouncilCostTracker } from './councilCostTracker.js';
import { ICouncilResultCache, CouncilResultCache } from './councilResultCache.js';
import { ICouncilIncrementalReview, CouncilIncrementalReview } from './councilIncrementalReview.js';
import { ICouncilStreamingUI, CouncilStreamingUI } from './councilStreamingUI.js';
import { ICouncilFixApplier, CouncilFixApplier } from './councilFixApplier.js';
import { ICouncilInteractiveDebate, CouncilInteractiveDebate } from './councilInteractiveDebate.js';
import { ICouncilSessionReplay, CouncilSessionReplay } from './councilSessionReplay.js';
import { ICouncilDiffView, CouncilDiffView } from './councilDiffView.js';
import { ICouncilLearningEngine, CouncilLearningEngine } from './councilLearningEngine.js';
import { ICouncilAutoPR, CouncilAutoPR } from './councilAutoPR.js';
import { ICouncilLazyLoader, CouncilLazyLoader } from './councilLazyLoader.js';
import { ICouncilRateLimiter, CouncilRateLimiter } from './councilRateLimiter.js';
import { ICouncilKeybindings, CouncilKeybindings } from './councilKeybindings.js';
import { ICouncilSearchFilter, CouncilSearchFilter } from './councilSearchFilter.js';
import { ICouncilCredentialManager, CouncilCredentialManager } from './councilCredentialManager.js';
import { ICouncilDataRetention, CouncilDataRetention } from './councilDataRetention.js';
import { ICouncilTelemetryService, CouncilTelemetryService } from './councilTelemetryService.js';
import { ICouncilCircuitBreaker, CouncilCircuitBreaker } from './councilCircuitBreaker.js';
import { ICouncilSessionEviction, CouncilSessionEviction } from './councilSessionEviction.js';
import { ICouncilRetry, CouncilRetry } from './councilRetry.js';
import { ICouncilContextWindow, CouncilContextWindow } from './councilContextWindow.js';
import { ICouncilModelCache, CouncilModelCache } from './councilModelCache.js';
import { ICouncilConnectionPool, CouncilConnectionPool } from './councilConnectionPool.js';
import { ICouncilTokenBudget, CouncilTokenBudget } from './councilTokenBudget.js';
import { ICouncilRequestDedup, CouncilRequestDedup } from './councilRequestDedup.js';
import { ICouncilHealthCheck, CouncilHealthCheck } from './councilHealthCheck.js';
import { ICouncilUndoRedo, CouncilUndoRedo } from './councilUndoRedo.js';
import { ICouncilDistributedCache, CouncilDistributedCache } from './councilDistributedCache.js';
import { ICouncilTelemetrySampling, CouncilTelemetrySampling } from './councilTelemetrySampling.js';
import { ICouncilSessionExport, CouncilSessionExport } from './councilSessionExport.js';
import { ICouncilPersonalityPersistence, CouncilPersonalityPersistence } from './councilPersonalityPersistence.js';
import { ICouncilBatchOperations, CouncilBatchOperations } from './councilBatchOperations.js';
import { ICouncilEnhancedOrchestrator, CouncilEnhancedOrchestrator } from './councilEnhancedOrchestrator.js';

registerSingleton(IAgentProfileManager, AgentProfileManager, InstantiationType.Delayed);
registerSingleton(ICouncilOrchestrator, CouncilOrchestrator, InstantiationType.Delayed);
registerSingleton(IConsensusManager, ConsensusManager, InstantiationType.Delayed);
registerSingleton(IEvidenceValidator, EvidenceValidator, InstantiationType.Delayed);
registerSingleton(IAdvancedConsensusEngine, AdvancedConsensusEngine, InstantiationType.Delayed);
registerSingleton(IDebateResolver, DebateResolver, InstantiationType.Delayed);
registerSingleton(ICouncilTestRunner, CouncilTestRunner, InstantiationType.Delayed);
registerSingleton(ICouncilMCPIntegration, CouncilMCPIntegration, InstantiationType.Delayed);
registerSingleton(IRedTeamAgent, RedTeamAgent, InstantiationType.Delayed);
registerSingleton(ICouncilCIRunner, CouncilCIRunner, InstantiationType.Delayed);
registerSingleton(ICouncilMemoryGraph, CouncilMemoryGraph, InstantiationType.Delayed);
registerSingleton(ICouncilPolicyEngine, CouncilPolicyEngine, InstantiationType.Delayed);
registerSingleton(ICouncilPRReviewBoard, CouncilPRReviewBoard, InstantiationType.Delayed);
registerSingleton(ICouncilGovernance, CouncilGovernance, InstantiationType.Delayed);
registerSingleton(ICouncilEnterprise, CouncilEnterprise, InstantiationType.Delayed);
registerSingleton(ICouncilSmartAgentSelector, CouncilSmartAgentSelector, InstantiationType.Delayed);
registerSingleton(ICouncilModelRouter, CouncilModelRouter, InstantiationType.Delayed);
registerSingleton(ICouncilSecretDetector, CouncilSecretDetector, InstantiationType.Delayed);
registerSingleton(ICouncilInputSanitizer, CouncilInputSanitizer, InstantiationType.Delayed);
registerSingleton(ICouncilNotificationService, CouncilNotificationService, InstantiationType.Delayed);
registerSingleton(ICouncilCostTracker, CouncilCostTracker, InstantiationType.Delayed);
registerSingleton(ICouncilResultCache, CouncilResultCache, InstantiationType.Delayed);
registerSingleton(ICouncilIncrementalReview, CouncilIncrementalReview, InstantiationType.Delayed);
registerSingleton(ICouncilStreamingUI, CouncilStreamingUI, InstantiationType.Delayed);
registerSingleton(ICouncilFixApplier, CouncilFixApplier, InstantiationType.Delayed);
registerSingleton(ICouncilInteractiveDebate, CouncilInteractiveDebate, InstantiationType.Delayed);
registerSingleton(ICouncilSessionReplay, CouncilSessionReplay, InstantiationType.Delayed);
registerSingleton(ICouncilDiffView, CouncilDiffView, InstantiationType.Delayed);
registerSingleton(ICouncilLearningEngine, CouncilLearningEngine, InstantiationType.Delayed);
registerSingleton(ICouncilAutoPR, CouncilAutoPR, InstantiationType.Delayed);
registerSingleton(ICouncilLazyLoader, CouncilLazyLoader, InstantiationType.Delayed);
registerSingleton(ICouncilRateLimiter, CouncilRateLimiter, InstantiationType.Delayed);
registerSingleton(ICouncilKeybindings, CouncilKeybindings, InstantiationType.Delayed);
registerSingleton(ICouncilSearchFilter, CouncilSearchFilter, InstantiationType.Delayed);
registerSingleton(ICouncilCredentialManager, CouncilCredentialManager, InstantiationType.Delayed);
registerSingleton(ICouncilDataRetention, CouncilDataRetention, InstantiationType.Delayed);
registerSingleton(ICouncilTelemetryService, CouncilTelemetryService, InstantiationType.Delayed);
registerSingleton(ICouncilCircuitBreaker, CouncilCircuitBreaker, InstantiationType.Delayed);
registerSingleton(ICouncilSessionEviction, CouncilSessionEviction, InstantiationType.Delayed);
registerSingleton(ICouncilRetry, CouncilRetry, InstantiationType.Delayed);
registerSingleton(ICouncilContextWindow, CouncilContextWindow, InstantiationType.Delayed);
registerSingleton(ICouncilModelCache, CouncilModelCache, InstantiationType.Delayed);
registerSingleton(ICouncilConnectionPool, CouncilConnectionPool, InstantiationType.Delayed);
registerSingleton(ICouncilTokenBudget, CouncilTokenBudget, InstantiationType.Delayed);
registerSingleton(ICouncilRequestDedup, CouncilRequestDedup, InstantiationType.Delayed);
registerSingleton(ICouncilHealthCheck, CouncilHealthCheck, InstantiationType.Delayed);
registerSingleton(ICouncilUndoRedo, CouncilUndoRedo, InstantiationType.Delayed);
registerSingleton(ICouncilDistributedCache, CouncilDistributedCache, InstantiationType.Delayed);
registerSingleton(ICouncilTelemetrySampling, CouncilTelemetrySampling, InstantiationType.Delayed);
registerSingleton(ICouncilSessionExport, CouncilSessionExport, InstantiationType.Delayed);
registerSingleton(ICouncilPersonalityPersistence, CouncilPersonalityPersistence, InstantiationType.Delayed);
registerSingleton(ICouncilBatchOperations, CouncilBatchOperations, InstantiationType.Delayed);
registerSingleton(ICouncilEnhancedOrchestrator, CouncilEnhancedOrchestrator, InstantiationType.Delayed);
