/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { Disposable, IDisposable } from '../../../../../../base/common/lifecycle.js';
import { createDecorator } from '../../../../../../platform/instantiation/common/instantiation.js';
import { ILogService } from '../../../../../../platform/log/common/log.js';
import { ICouncilOrchestrator, CouncilResult } from './councilOrchestrator.js';
import { ICouncilFixApplier, CodeFix, FixApplicationResult } from './councilFixApplier.js';
import { Event, Emitter } from '../../../../../../base/common/event.js';
import { generateUuid } from '../../../../../../base/common/uuid.js';

export const ICouncilAutoPR = createDecorator<ICouncilAutoPR>('councilAutoPR');

export interface AutoPRConfig {
	readonly autoCreatePR: boolean;
	readonly autoApplyFixes: boolean;
	readonly maxFilesToModify: number;
	readonly requireHumanApproval: boolean;
	readonly branchPrefix: string;
	readonly prTemplate: string;
	readonly targetBranch: string;
	readonly labels: string[];
	readonly reviewers: string[];
}

export interface AutoPRResult {
	readonly prId: string;
	readonly branchName: string;
	readonly prNumber?: number;
	readonly prUrl?: string;
	readonly filesModified: string[];
	readonly fixResults: FixApplicationResult[];
	readonly councilResult: CouncilResult;
	readonly createdAt: number;
	readonly status: 'created' | 'failed' | 'pending_approval';
}

export interface AutoPRRequest {
	readonly issue: string;
	readonly context: string;
	readonly workspaceRoot: string;
	readonly config?: Partial<AutoPRConfig>;
}

export interface ICouncilAutoPR extends IDisposable {
	readonly _serviceBrand: undefined;

	readonly onPRCreated: Event<AutoPRResult>;

	createAutoPR(request: AutoPRRequest): Promise<AutoPRResult>;
	generateBranchName(issue: string): string;
	generatePRTitle(issue: string): string;
	generatePRDescription(issue: string, context: string, fixResults: FixApplicationResult[]): string;
	getDefaultConfig(): AutoPRConfig;
}

const DEFAULT_CONFIG: AutoPRConfig = {
	autoCreatePR: true,
	autoApplyFixes: true,
	maxFilesToModify: 5,
	requireHumanApproval: true,
	branchPrefix: 'council/auto-fix',
	prTemplate: '## Council Auto-Fix\n\nThis PR was automatically generated by the Agent Council system.\n\n### Issue\n{issue}\n\n### Changes\n{changes}\n\n### Council Analysis\n{analysis}',
	targetBranch: 'main',
	labels: ['council-auto-fix', 'automated'],
	reviewers: []
};

export class CouncilAutoPR extends Disposable implements ICouncilAutoPR {
	declare readonly _serviceBrand: undefined;

	private readonly _onPRCreated = this._register(new Emitter<AutoPRResult>());
	readonly onPRCreated = this._onPRCreated.event;

	constructor(
		@ICouncilOrchestrator private readonly orchestrator: ICouncilOrchestrator,
		@ICouncilFixApplier private readonly fixApplier: ICouncilFixApplier,
		@ILogService private readonly logService: ILogService
	) {
		super();
	}

	public async createAutoPR(request: AutoPRRequest): Promise<AutoPRResult> {
		const config = { ...DEFAULT_CONFIG, ...request.config };
		const prId = generateUuid();

		this.logService.info(`[Council AutoPR] Creating PR for: ${request.issue.substring(0, 100)}...`);

		try {
			const councilRequest = `Analyze and fix the following issue:\n\nIssue: ${request.issue}\n\nContext: ${request.context}\n\nProvide specific code fixes with file paths and line numbers.`;

			const councilResult = await this.orchestrator.executeSession(councilRequest);

			const fixes = this.fixApplier.parseFixFromMarkdown(councilResult.finalResponse);
			const limitedFixes = fixes.slice(0, config.maxFilesToModify);

			let fixResults: FixApplicationResult[] = [];

			if (config.autoApplyFixes && limitedFixes.length > 0) {
				const workspaceUri = { fsPath: request.workspaceRoot } as any;
				fixResults = await this.fixApplier.applyFixes(limitedFixes, workspaceUri);
			}

			const branchName = this.generateBranchName(request.issue);
			const modifiedFiles = fixResults.filter(r => r.success).map(r => r.file);

			const result: AutoPRResult = {
				prId,
				branchName,
				filesModified: modifiedFiles,
				fixResults,
				councilResult,
				createdAt: Date.now(),
				status: config.requireHumanApproval ? 'pending_approval' : 'created'
			};

			this._onPRCreated.fire(result);
			this.logService.info(`[Council AutoPR] PR created: ${branchName} (${modifiedFiles.length} files modified)`);

			return result;
		} catch (error) {
			this.logService.error(`[Council AutoPR] Failed: ${error}`);
			throw error;
		}
	}

	public generateBranchName(issue: string): string {
		const sanitized = issue
			.toLowerCase()
			.replace(/[^a-z0-9\s-]/g, '')
			.replace(/\s+/g, '-')
			.substring(0, 50)
			.replace(/-+$/, '');

		const shortId = generateUuid().substring(0, 8);
		return `${DEFAULT_CONFIG.branchPrefix}/${sanitized}-${shortId}`;
	}

	public generatePRTitle(issue: string): string {
		const truncated = issue.length > 80 ? issue.substring(0, 77) + '...' : issue;
		return `🤖 Council Auto-Fix: ${truncated}`;
	}

	public generatePRDescription(
		issue: string,
		context: string,
		fixResults: FixApplicationResult[]
	): string {
		const successfulFixes = fixResults.filter(r => r.success);
		const failedFixes = fixResults.filter(r => !r.success);

		const changes = successfulFixes.map(f => `- ${f.file}: ${f.fixId}`).join('\n') || 'No changes applied';

		return DEFAULT_CONFIG.prTemplate
			.replace('{issue}', issue)
			.replace('{changes}', changes)
			.replace('{analysis}', context.substring(0, 2000));
	}

	public getDefaultConfig(): AutoPRConfig {
		return { ...DEFAULT_CONFIG };
	}
}
