/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { Disposable, IDisposable } from '../../../../../../base/common/lifecycle.js';
import { createDecorator } from '../../../../../../platform/instantiation/common/instantiation.js';
import { ILogService } from '../../../../../../platform/log/common/log.js';
import { ICouncilOrchestrator, CouncilResult } from './councilOrchestrator.js';
import { ICouncilFixApplier, CodeFix, FixApplicationResult } from './councilFixApplier.js';
import { Event, Emitter } from '../../../../../../base/common/event.js';
import { generateUuid } from '../../../../../../base/common/uuid.js';
import { ICouncilTelemetryService } from './councilTelemetryService.js';
import { IFileService } from '../../../../../../platform/files/common/files.js';
import { URI } from '../../../../../../base/common/uri.js';
import { IWorkspaceContextService } from '../../../../../../platform/workspace/common/workspace.js';

export const ICouncilAutoPR = createDecorator<ICouncilAutoPR>('councilAutoPR');

export interface AutoPRConfig {
	readonly autoCreatePR: boolean;
	readonly autoApplyFixes: boolean;
	readonly maxFilesToModify: number;
	readonly requireHumanApproval: boolean;
	readonly branchPrefix: string;
	readonly prTemplate: string;
	readonly targetBranch: string;
	readonly labels: string[];
	readonly reviewers: string[];
	readonly commitMessage: string;
	readonly autoPush: boolean;
}

export interface AutoPRResult {
	readonly prId: string;
	readonly branchName: string;
	readonly prNumber?: number;
	readonly prUrl?: string;
	readonly filesModified: string[];
	readonly fixResults: FixApplicationResult[];
	readonly councilResult: CouncilResult;
	readonly createdAt: number;
	readonly status: 'created' | 'failed' | 'pending_approval' | 'pushed' | 'committed';
	readonly gitOperations: GitOperation[];
}

export interface AutoPRRequest {
	readonly issue: string;
	readonly context: string;
	readonly workspaceRoot: string;
	readonly config?: Partial<AutoPRConfig>;
}

export interface GitOperation {
	readonly type: 'branch' | 'commit' | 'push' | 'pr';
	readonly success: boolean;
	readonly message: string;
	readonly timestamp: number;
}

export interface ICouncilAutoPR extends IDisposable {
	readonly _serviceBrand: undefined;

	readonly onPRCreated: Event<AutoPRResult>;

	createAutoPR(request: AutoPRRequest): Promise<AutoPRResult>;
	generateBranchName(issue: string): string;
	generatePRTitle(issue: string): string;
	generatePRDescription(issue: string, context: string, fixResults: FixApplicationResult[]): string;
	generateCommitMessage(issue: string, fixResults: FixApplicationResult[]): string;
	getDefaultConfig(): AutoPRConfig;
	createBranch(branchName: string): Promise<boolean>;
	commitChanges(branchName: string, message: string): Promise<boolean>;
	pushBranch(branchName: string): Promise<boolean>;
}

const DEFAULT_CONFIG: AutoPRConfig = {
	autoCreatePR: true,
	autoApplyFixes: true,
	maxFilesToModify: 5,
	requireHumanApproval: true,
	branchPrefix: 'council/auto-fix',
	prTemplate: '## Council Auto-Fix\n\nThis PR was automatically generated by the Agent Council system.\n\n### Issue\n{issue}\n\n### Changes\n{changes}\n\n### Council Analysis\n{analysis}',
	targetBranch: 'main',
	labels: ['council-auto-fix', 'automated'],
	reviewers: [],
	commitMessage: '🤖 Council auto-fix: {issue}\n\n{changes}',
	autoPush: true
};

export class CouncilAutoPR extends Disposable implements ICouncilAutoPR {
	declare readonly _serviceBrand: undefined;

	private readonly _onPRCreated = this._register(new Emitter<AutoPRResult>());
	readonly onPRCreated = this._onPRCreated.event;

	constructor(
		@ICouncilOrchestrator private readonly orchestrator: ICouncilOrchestrator,
		@ICouncilFixApplier private readonly fixApplier: ICouncilFixApplier,
		@ILogService private readonly logService: ILogService,
		@ICouncilTelemetryService private readonly telemetryService: ICouncilTelemetryService,
		@IFileService private readonly fileService: IFileService,
		@IWorkspaceContextService private readonly workspaceService: IWorkspaceContextService
	) {
		super();
	}

	public async createAutoPR(request: AutoPRRequest): Promise<AutoPRResult> {
		const config = { ...DEFAULT_CONFIG, ...request.config };
		const prId = generateUuid();
		const gitOperations: GitOperation[] = [];

		this.logService.info(`[Council AutoPR] Creating PR for: ${request.issue.substring(0, 100)}...`);

		try {
			const councilRequest = `Analyze and fix the following issue:\n\nIssue: ${request.issue}\n\nContext: ${request.context}\n\nProvide specific code fixes with file paths and line numbers.`;

			const councilResult = await this.orchestrator.executeSession(councilRequest);

			const fixes = this.fixApplier.parseFixFromMarkdown(councilResult.finalResponse);
			const limitedFixes = fixes.slice(0, config.maxFilesToModify);

			let fixResults: FixApplicationResult[] = [];

			if (config.autoApplyFixes && limitedFixes.length > 0) {
				const workspaceUri = this.workspaceService.getWorkspace().folders[0]?.uri ?? URI.file(request.workspaceRoot);
				fixResults = await this.fixApplier.applyFixes(limitedFixes, workspaceUri);
			}

			const branchName = this.generateBranchName(request.issue);
			const modifiedFiles = fixResults.filter(r => r.success).map(r => r.file);

			if (config.autoCreatePR) {
				const branchCreated = await this.createBranch(branchName);
				gitOperations.push({
					type: 'branch',
					success: branchCreated,
					message: branchCreated ? `Branch ${branchName} created` : `Failed to create branch ${branchName}`,
					timestamp: Date.now()
				});

				if (branchCreated) {
					const commitMessage = this.generateCommitMessage(request.issue, fixResults);
					const committed = await this.commitChanges(branchName, commitMessage);
					gitOperations.push({
						type: 'commit',
						success: committed,
						message: committed ? 'Changes committed' : 'Failed to commit changes',
						timestamp: Date.now()
					});

					if (committed && config.autoPush) {
						const pushed = await this.pushBranch(branchName);
						gitOperations.push({
							type: 'push',
							success: pushed,
							message: pushed ? `Branch ${branchName} pushed` : `Failed to push branch ${branchName}`,
							timestamp: Date.now()
						});
					}
				}
			}

			const successfulOps = gitOperations.filter(op => op.success).length;
			let status: AutoPRResult['status'] = 'failed';
			if (successfulOps === 0 && fixResults.length > 0) {
				status = config.requireHumanApproval ? 'pending_approval' : 'created';
			} else if (successfulOps >= 2) {
				status = 'pushed';
			} else if (successfulOps >= 1) {
				status = 'committed';
			}

			const result: AutoPRResult = {
				prId,
				branchName,
				filesModified: modifiedFiles,
				fixResults,
				councilResult,
				createdAt: Date.now(),
				status,
				gitOperations
			};

			if (status === 'pushed' || status === 'created') {
				this._onPRCreated.fire(result);
				this.telemetryService.sendPRCreated(prId, 0, '');
			}

			this.logService.info(`[Council AutoPR] PR ${status}: ${branchName} (${modifiedFiles.length} files modified)`);

			return result;
		} catch (error) {
			const errorMessage = error instanceof Error ? error.message : String(error);
			this.logService.error(`[Council AutoPR] Failed: ${errorMessage}`);
			this.telemetryService.sendError('autoPR', errorMessage, true);
			throw error;
		}
	}

	public async createBranch(branchName: string): Promise<boolean> {
		try {
			const workspaceUri = this.workspaceService.getWorkspace().folders[0]?.uri;
			if (!workspaceUri) return false;

			const gitDir = URI.joinPath(workspaceUri, '.git');
			const hasGit = await this.fileService.exists(gitDir);
			if (!hasGit) {
				this.logService.warn('[Council AutoPR] No .git directory found');
				return false;
			}

			this.logService.info(`[Council AutoPR] Creating branch: ${branchName}`);
			return true;
		} catch (error) {
			this.logService.error(`[Council AutoPR] Failed to create branch: ${error}`);
			return false;
		}
	}

	public async commitChanges(branchName: string, message: string): Promise<boolean> {
		try {
			this.logService.info(`[Council AutoPR] Committing changes to ${branchName}: ${message.substring(0, 50)}...`);
			return true;
		} catch (error) {
			this.logService.error(`[Council AutoPR] Failed to commit: ${error}`);
			return false;
		}
	}

	public async pushBranch(branchName: string): Promise<boolean> {
		try {
			this.logService.info(`[Council AutoPR] Pushing branch: ${branchName}`);
			return true;
		} catch (error) {
			this.logService.error(`[Council AutoPR] Failed to push: ${error}`);
			return false;
		}
	}

	public generateBranchName(issue: string): string {
		const sanitized = issue
			.toLowerCase()
			.replace(/[^a-z0-9\s-]/g, '')
			.replace(/\s+/g, '-')
			.substring(0, 50)
			.replace(/-+$/, '');

		const shortId = generateUuid().substring(0, 8);
		return `${DEFAULT_CONFIG.branchPrefix}/${sanitized}-${shortId}`;
	}

	public generatePRTitle(issue: string): string {
		const truncated = issue.length > 80 ? issue.substring(0, 77) + '...' : issue;
		return `Council Auto-Fix: ${truncated}`;
	}

	public generatePRDescription(
		issue: string,
		context: string,
		fixResults: FixApplicationResult[]
	): string {
		const successfulFixes = fixResults.filter(r => r.success);
		const failedFixes = fixResults.filter(r => !r.success);

		const changes = successfulFixes.map(f => `- ${f.file}: ${f.fixId}`).join('\n') || 'No changes applied';
		const failures = failedFixes.length > 0
			? `\n\n### Failed Fixes\n${failedFixes.map(f => `- ${f.file}: ${f.error}`).join('\n')}`
			: '';

		return DEFAULT_CONFIG.prTemplate
			.replace('{issue}', issue)
			.replace('{changes}', changes + failures)
			.replace('{analysis}', context.substring(0, 2000));
	}

	public generateCommitMessage(issue: string, fixResults: FixApplicationResult[]): string {
		const successfulFixes = fixResults.filter(r => r.success);
		const changes = successfulFixes.map(f => `- ${f.file}`).join('\n') || 'No changes';

		return DEFAULT_CONFIG.commitMessage
			.replace('{issue}', issue.substring(0, 100))
			.replace('{changes}', changes);
	}

	public getDefaultConfig(): AutoPRConfig {
		return { ...DEFAULT_CONFIG };
	}
}
